site_name: 金牛智道一号的财富安全世界
site_description: 金牛智道一号的财富安全世界，记录投资成长的一点一滴
site_author: 邱承
copyright: 金牛智道 2021
site_url: https://wealth_safe_world.markqiu.cn/
base_url: /
repo_name: markqiu/jinniuai_wealth_safe_world
repo_url: https://github.com/markqiu/jinniuai_wealth_safe_world
theme:
  name: 'material'
  logo: 'images/logo.png'
  favicon: 'images/logo.png'
  language: zh
  palette:
      primary: blue
      accent: indigo
      scheme: default
  tabs: true
  #instant: true
  features:
    - search.suggest
    - search.highlight
markdown_extensions:
  - abbr
  - admonition
  - codehilite:
      linenums: true
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde
plugins:
  - search:
      prebuild_index: false
  - minify:
      minify_html: true
  - git-revision-date-localized:
      type: datetime
  - awesome-pages
  - macros
